# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line.
SPHINXOPTS		=
SPHINXBUILD		= python -msphinx
SPHINXPROJ		= pyarcher
SOURCEDIR		= .
BUILDDIR		= _build

# Put it first so that "make" without argument is like "make help".
help:
		@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(0)

.PHONY: help Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(0) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
		@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(0)